"""System-level engagement loop — Decepticon's Ralph Mode.

Follows the Deep Agents ralph_mode.py pattern: a Python async while loop
that invokes LangGraph agents with fresh context per iteration. The
filesystem (workspace/) and Neo4j KG serve as memory across iterations.

Two autonomous phases (planning is handled by the decepticon main agent):
  Phase 2 (attack):    Ralph loop iterates OPPLAN objectives with fresh agent per iteration
  Phase 3 (vaccine):   Batch defense/verification for all accumulated findings

Prerequisites:
  - workspace/plan/opplan.json must exist (generated by decepticon agent via Soundwave)
  - workspace/plan/roe.json should exist (scope constraints)

Usage:
    loop = EngagementLoop(workspace, config)
    state = await loop.run()  # starts at ATTACK phase
"""

from __future__ import annotations

import json
import os
import re
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import httpx

from decepticon.core.engagement import (
    EngagementConfig,
    EngagementPhase,
    EngagementState,
    IterationResult,
    VaccineMode,
)
from decepticon.core.env_verifier import EnvironmentVerifier
from decepticon.core.logging import get_logger
from decepticon.core.schemas import OPPLAN, Objective, ObjectiveStatus
from decepticon.schemas.defense_brief import (
    DefenseActionType,
    DefenseBrief,
    DefenseRecommendation,
    ReAttackOutcome,
    VerificationResult,
)
from decepticon.schemas.env_verification import CheckPhase
from decepticon.tools.bash.bash import get_sandbox
from decepticon.tools.research.poc import sandbox_runner

log = get_logger("core.engagement_loop")


class EngagementLoop:
    """System-level engagement orchestrator following ralph_mode.py pattern."""

    def __init__(self, workspace: Path, config: EngagementConfig) -> None:
        self._workspace = workspace
        self._config = config
        self._state: EngagementState | None = None
        self._opplan: OPPLAN | None = None
        sandbox = get_sandbox()
        self._verifier: EnvironmentVerifier | None = (
            EnvironmentVerifier(self._workspace, sandbox_runner(sandbox))
            if sandbox is not None
            else None
        )

    async def run(self) -> EngagementState:
        """Main loop — executes attack and vaccine phases.

        Prerequisites: OPPLAN must already exist at workspace/plan/opplan.json.
        The decepticon main agent handles the planning phase (Soundwave interview)
        before triggering this loop.
        """
        # Load or create state
        self._state = EngagementState.load(self._workspace) or EngagementState(
            max_iterations=self._config.max_iterations,
            workspace=str(self._workspace),
            target=self._config.target,
            phase=EngagementPhase.ATTACK,
        )
        assert self._state is not None
        if self._state.resumed_at is None and self._state.iteration > 0:
            self._state.resumed_at = datetime.now(timezone.utc)

        # Verify OPPLAN exists (must be created by decepticon agent before loop starts)
        self._opplan = self._load_opplan()
        if self._opplan is None:
            log.error(
                "OPPLAN not found at %s/plan/opplan.json — "
                "decepticon agent must generate it before starting the loop",
                self._workspace,
            )
            self._state.phase = EngagementPhase.COMPLETE
            self._state.save(self._workspace)
            return self._state

        log.info(
            "Engagement loop started: phase=%s iteration=%d objectives=%d",
            self._state.phase,
            self._state.iteration,
            len(self._opplan.objectives),
        )
        # Recover stale in-progress objectives from a previous crash/restart.
        # The loop marks objectives IN_PROGRESS before invoking the agent and
        # updates to COMPLETED/BLOCKED after. If the process dies between those
        # two writes, the objective is orphaned and never retried.
        self._recover_stale_objectives()

        try:
            while not self._state.is_complete:
                match self._state.phase:
                    case EngagementPhase.ATTACK:
                        await self._run_attack_phase()
                    case EngagementPhase.VACCINE:
                        await self._run_vaccine_phase()
                    case EngagementPhase.COMPLETE:
                        break
                    case _:
                        # PLANNING phase is handled by decepticon agent, not this loop
                        self._state.phase = EngagementPhase.ATTACK

                self._state.save(self._workspace)

        except KeyboardInterrupt:
            log.info("Interrupt received — saving state for resume")
            if self._state:
                self._state.save(self._workspace)
            raise

        self._state.phase = EngagementPhase.COMPLETE
        self._state.save(self._workspace)
        log.info("Engagement complete: %s", self._state.summary)
        return self._state

    # ── Phase runners ──────────────────────────────────────────────────────────

    async def _run_attack_phase(self) -> None:
        """Ralph-pattern attack loop — one objective per iteration with a fresh agent."""
        assert self._state is not None

        # Reload opplan from disk each iteration (fresh context = ralph pattern)
        self._opplan = self._load_opplan()
        if self._opplan is None:
            log.error("opplan.json missing during attack phase — returning to planning")
            self._state.phase = EngagementPhase.PLANNING
            return

        obj = self._next_pending_objective()
        if obj is None:
            log.info("All objectives processed — transitioning to vaccine phase")
            self._state.phase = EngagementPhase.VACCINE
            return

        self._state.current_objective_id = obj.id
        self._state.iteration += 1

        agent_name = self._select_agent(obj)
        prompt = self._build_attack_prompt(obj)

        log.info(
            "Attack iteration %d: objective=%s agent=%s",
            self._state.iteration,
            obj.id,
            agent_name,
        )

        start_time = time.time()
        # Mark in-progress before invoking
        self._update_opplan_objective(obj.id, ObjectiveStatus.IN_PROGRESS)

        result: IterationResult
        new_status: ObjectiveStatus
        try:
            response = await self._invoke_agent(agent_name, prompt)
            result = self._parse_objective_result(response, obj, agent_name, start_time)

            self._state.iteration_history.append(result)

            if result.outcome == "PASSED":
                new_status = ObjectiveStatus.COMPLETED
                self._state.objectives_completed.append(obj.id)
            else:
                new_status = ObjectiveStatus.BLOCKED
                self._state.objectives_blocked.append(obj.id)
        except KeyboardInterrupt:
            raise
        except Exception as exc:
            log.exception("Objective %s crashed mid-execution — marking BLOCKED", obj.id)
            new_status = ObjectiveStatus.BLOCKED
            self._state.objectives_blocked.append(obj.id)
            result = IterationResult(
                objective_id=obj.id,
                agent_used=agent_name,
                outcome="BLOCKED",
                findings_produced=[],
                duration_seconds=round(time.time() - start_time, 2),
                raw_output=f"Exception: {exc}",
            )
            self._state.iteration_history.append(result)

        self._update_opplan_objective(obj.id, new_status)

        # Track findings
        for finding_ref in result.findings_produced:
            if finding_ref not in self._state.findings_discovered:
                self._state.findings_discovered.append(finding_ref)

        # Immediate vaccine mode: apply defense right after finding discovery
        if self._config.vaccine_mode == VaccineMode.IMMEDIATE and result.findings_produced:
            log.info(
                "Immediate vaccine mode — applying defense for %d finding(s)",
                len(result.findings_produced),
            )
            await self._apply_defenses(result.findings_produced)

    async def _run_vaccine_phase(self) -> None:
        """Batch defense/verification for all accumulated findings.

        Merges findings tracked in state with those discovered on disk
        (workspace/findings/FIND-*.md) so that findings written by the attack
        agents but not captured in state are also processed.
        """
        assert self._state is not None

        # Scan filesystem for FIND-*.md files and merge with state-tracked refs
        fs_findings = self._scan_findings()
        tracked = set(self._state.findings_discovered)
        for ref in fs_findings:
            if ref not in tracked:
                log.info("Vaccine phase: adding filesystem-discovered finding %s to state", ref)
                self._state.findings_discovered.append(ref)
                tracked.add(ref)

        # A finding is unprocessed if it has no verification result on disk
        unprocessed = [
            f
            for f in self._state.findings_discovered
            if not (self._workspace / f"verification-{f}.json").exists()
        ]

        if not unprocessed:
            log.info("Vaccine phase: no unprocessed findings — transitioning to COMPLETE")
            self._state.phase = EngagementPhase.COMPLETE
            return

        log.info(
            "Vaccine phase: processing %d finding(s): %s", len(unprocessed), ", ".join(unprocessed)
        )
        await self._apply_defenses(unprocessed)
        self._state.phase = EngagementPhase.COMPLETE

    # ── Helpers ────────────────────────────────────────────────────────────────

    async def _apply_defenses(self, finding_refs: list[str]) -> None:
        """Generate a defense brief and invoke the defender agent for each finding.

        For each finding:
          1. Parses the finding markdown to build a structured DefenseBrief
          2. Writes brief to workspace/defense-brief.json
          3. Invokes the defender agent with a prompt pointing at the brief
          4. Loads the verification result written by the agent and logs outcome
        """
        for finding_ref in finding_refs:
            brief_path = self._workspace / "defense-brief.json"
            brief = self._generate_defense_brief(finding_ref)
            if brief is None:
                log.warning("Could not generate defense brief for %s — skipping", finding_ref)
                continue
            try:
                brief_path.write_text(brief.model_dump_json(indent=2), encoding="utf-8")
                log.info(
                    "Defense brief written for %s (%d recommended action(s))",
                    finding_ref,
                    len(brief.recommended_actions),
                )
            except OSError as exc:
                log.error("Could not write defense brief for %s: %s", finding_ref, exc)
                continue

            defense_prompt = (
                f"## Defense Action Required\n\n"
                f"Finding: {finding_ref}\n"
                f"Brief: {brief_path}\n"
                f"Workspace: {self._workspace}\n\n"
                "Read the defense-brief.json, execute the recommended defense actions, "
                "re-attack to verify, and write verification results to "
                f"verification-{finding_ref}.json. "
                "Signal DEFENSE COMPLETE or DEFENSE FAILED when done."
            )

            # Pre-defense environment snapshot for grounded verification
            use_env = os.environ.get("VACCINE_USE_ENV_VERIFIER", "1") != "0"
            if use_env and self._verifier is not None:
                spec = self._verifier.load_spec(finding_ref)
                if spec is not None:
                    pre = await self._verifier.capture_state(spec, phase=CheckPhase.PRE_DEFENSE)
                    self._verifier.persist_snapshot(pre)

            log.info("Invoking defender agent for %s", finding_ref)
            await self._invoke_agent("defender", defense_prompt)

            # Env-grounded verification first; fall back to legacy LLM result
            result = await self._verify_finding_env(finding_ref)
            if result is not None:
                if result.re_attack_outcome == ReAttackOutcome.BLOCKED:
                    log.info("Defense VERIFIED for %s — re-attack blocked", finding_ref)
                else:
                    log.warning(
                        "Defense result for %s: outcome=%s",
                        finding_ref,
                        result.re_attack_outcome,
                    )
            else:
                log.warning(
                    "No verification result for %s after defender ran — "
                    "defense agent may not have written verification-%s.json",
                    finding_ref,
                    finding_ref,
                )

    async def _verify_finding_env(self, finding_ref: str) -> VerificationResult | None:
        """Try env-grounded verification first; fall back to legacy LLM result."""
        use_env = os.environ.get("VACCINE_USE_ENV_VERIFIER", "1") != "0"
        if use_env and self._verifier is not None:
            spec = self._verifier.load_spec(finding_ref)
            if spec is not None:
                post = await self._verifier.capture_state(spec, phase=CheckPhase.POST_DEFENSE)
                pre = self._verifier.load_snapshot(finding_ref, CheckPhase.PRE_DEFENSE)
                evidence = await self._verifier.verify_blocked(spec, pre=pre, post=post)
                reward = self._verifier.compute_reward(evidence)
                self._verifier.persist_evidence(evidence)
                self._verifier.persist_reward(reward)
                return VerificationResult(
                    finding_ref=finding_ref,
                    defense_actions_applied=[],
                    re_attack_outcome=evidence.re_attack_outcome,
                    re_attack_details=(
                        f"env-verified reward={reward.reward:.1f} "
                        f"poc_hash={evidence.poc_evidence.output_hash}"
                    ),
                )
        return self._load_verification_result(finding_ref)

    def _scan_findings(self) -> list[str]:
        """Scan workspace/findings/ for FIND-*.md files.

        Returns a sorted list of finding refs (e.g. ``["FIND-001", "FIND-002"]``).
        """
        findings_dir = self._workspace / "findings"
        if not findings_dir.is_dir():
            log.debug("Findings directory does not exist: %s", findings_dir)
            return []
        refs = sorted(p.stem for p in findings_dir.glob("FIND-*.md"))
        log.debug("Scanned %d finding(s) from %s", len(refs), findings_dir)
        return refs

    def _load_verification_result(self, finding_ref: str) -> VerificationResult | None:
        """Load workspace/verification-{finding_ref}.json if it exists."""
        result_path = self._workspace / f"verification-{finding_ref}.json"
        if not result_path.exists():
            log.debug("Verification result not found: %s", result_path)
            return None
        try:
            data = json.loads(result_path.read_text(encoding="utf-8"))
            return VerificationResult.model_validate(data)
        except (OSError, ValueError) as exc:
            log.error("Failed to load verification result %s: %s", result_path, exc)
            return None

    def _generate_defense_brief(self, finding_ref: str) -> DefenseBrief | None:
        """Parse a finding markdown file and produce a structured DefenseBrief.

        Returns ``None`` only when the finding file cannot be read.
        Falls back to safe defaults when optional fields are absent.
        """
        finding_path = self._workspace / "findings" / f"{finding_ref}.md"
        if not finding_path.exists():
            log.warning("Finding file not found: %s", finding_path)
            return None
        try:
            content = finding_path.read_text(encoding="utf-8")
        except OSError as exc:
            log.error("Could not read finding %s: %s", finding_path, exc)
            return None

        lines = content.splitlines()
        title = "Unknown Finding"
        severity = "medium"
        attack_vector = ""
        affected_assets: list[str] = []
        evidence_summary = ""

        # Title: first H1 heading
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("# "):
                title = stripped[2:].strip()
                break

        # Severity: line containing "**Severity**:" or "Severity:"
        for line in lines:
            lower = line.lower()
            if "severity" in lower and ":" in lower:
                parts = line.split(":", 1)
                if len(parts) == 2:
                    candidate = parts[1].strip().strip("*").strip().lower()
                    if candidate in {"critical", "high", "medium", "low", "informational"}:
                        severity = candidate
                        break

        # Attack vector: line containing "Attack Vector:" or a following paragraph
        capture_vector = False
        vector_lines: list[str] = []
        for line in lines:
            lower = line.lower()
            if "attack vector" in lower and ":" in lower:
                parts = line.split(":", 1)
                if len(parts) == 2 and parts[1].strip():
                    vector_lines = [parts[1].strip()]
                    break
                capture_vector = True
                continue
            if capture_vector:
                stripped = line.strip()
                if stripped.startswith("#") or (stripped.startswith("**") and ":" in stripped):
                    break
                if stripped:
                    vector_lines.append(stripped)
                    if len(vector_lines) >= 3:
                        break
        if vector_lines:
            attack_vector = " ".join(vector_lines)

        # Affected assets: lines under "**Affected**:" or "**Assets**:"
        capture_assets = False
        for line in lines:
            lower = line.lower()
            if ("affected" in lower or "assets" in lower) and ":" in lower:
                parts = line.split(":", 1)
                if len(parts) == 2 and parts[1].strip():
                    for asset in parts[1].split(","):
                        asset = asset.strip()
                        if asset:
                            affected_assets.append(asset)
                    break
                capture_assets = True
                continue
            if capture_assets:
                stripped = line.strip()
                if stripped.startswith("#") or (stripped.startswith("**") and ":" in stripped):
                    break
                if stripped.startswith("-") or stripped.startswith("*"):
                    asset = stripped.lstrip("-* ").strip()
                    if asset:
                        affected_assets.append(asset)

        # Evidence summary: first non-empty line after "## Evidence" heading
        capture_evidence = False
        for line in lines:
            stripped = line.strip()
            if stripped.lower() in {"## evidence", "### evidence"}:
                capture_evidence = True
                continue
            if capture_evidence:
                if stripped.startswith("#"):
                    break
                if stripped:
                    evidence_summary = stripped
                    break

        recommended_actions = self._infer_recommendations(attack_vector, severity)

        return DefenseBrief(
            finding_ref=finding_ref,
            finding_title=title,
            severity=severity,
            attack_vector=attack_vector,
            affected_assets=affected_assets,
            recommended_actions=recommended_actions,
            evidence_summary=evidence_summary,
        )

    def _infer_recommendations(
        self, attack_vector: str, severity: str
    ) -> list[DefenseRecommendation]:
        """Infer defensive recommendations from attack vector keywords."""
        lower = attack_vector.lower()
        recommendations: list[DefenseRecommendation] = []
        priority = 1

        if any(kw in lower for kw in ("port", "tcp", "udp", "service", "listen")):
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.BLOCK_PORT,
                    target="affected-port",
                    priority=priority,
                    rationale=(
                        "Attack vector references a network port or listening service — "
                        "block inbound access as an immediate containment measure"
                    ),
                )
            )
            priority += 1

        if any(kw in lower for kw in ("ssh", "ftp", "telnet", "smb", "rdp", "vnc")):
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.DISABLE_SERVICE,
                    target="affected-service",
                    priority=priority,
                    rationale=(
                        "Attack vector references a remote-access protocol — "
                        "disable or harden the service to remove the attack surface"
                    ),
                )
            )
            priority += 1

        if any(kw in lower for kw in ("credential", "password", "token", "key", "secret", "auth")):
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.REVOKE_CREDENTIAL,
                    target="compromised-credential",
                    priority=priority,
                    rationale=(
                        "Attack vector involves credentials or authentication — "
                        "revoke and rotate affected credentials immediately"
                    ),
                )
            )
            priority += 1

        if any(kw in lower for kw in ("config", "misconfigur", "permission", "acl", "setting")):
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.UPDATE_CONFIG,
                    target="affected-config",
                    priority=priority,
                    rationale=(
                        "Attack vector references a misconfiguration — "
                        "update the relevant configuration to enforce secure defaults"
                    ),
                )
            )
            priority += 1

        if any(kw in lower for kw in ("process", "pid", "daemon", "spawn", "exec")):
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.KILL_PROCESS,
                    target="affected-process",
                    priority=priority,
                    rationale=(
                        "Attack vector involves a running process — "
                        "terminate the process to halt active exploitation"
                    ),
                )
            )
            priority += 1

        # Always recommend a firewall rule for critical/high findings with no other actions
        if severity in {"critical", "high"} and not recommendations:
            recommendations.append(
                DefenseRecommendation(
                    action_type=DefenseActionType.ADD_FIREWALL_RULE,
                    target="affected-host",
                    priority=1,
                    rationale=(
                        f"High-severity finding ({severity}) with no specific vector keywords — "
                        "add a restrictive firewall rule as a precautionary measure"
                    ),
                )
            )

        return recommendations

    def _select_agent(self, objective: Objective) -> str:
        """Map objective phase to a LangGraph assistant_id."""
        return self._config.agent_selection.get(objective.phase.value, "recon")

    async def _invoke_agent(self, agent_name: str, prompt: str) -> str:
        """POST a run to the LangGraph API and return the final message content.

        Uses httpx (async, lightweight) to avoid hard dependency on langgraph_sdk.
        If the API is unreachable the error is logged and an error string is
        returned — the loop continues rather than crashing.
        """
        thread_id = str(uuid.uuid4())
        url = f"{self._config.langgraph_url}/runs"
        payload = {
            "assistant_id": agent_name,
            "thread_id": thread_id,
            "input": {"messages": [{"role": "human", "content": prompt}]},
        }

        log.info("Invoking agent: name=%s thread=%s url=%s", agent_name, thread_id, url)

        try:
            async with httpx.AsyncClient(timeout=600.0) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()

            # Extract the final assistant message from the run result
            output = self._extract_message(data)
            log.debug("Agent %s responded (%.80s...)", agent_name, output)
            return output

        except httpx.ConnectError as exc:
            msg = f"[API_UNREACHABLE] Could not connect to LangGraph at {self._config.langgraph_url}: {exc}"
            log.error(msg)
            return msg
        except httpx.HTTPStatusError as exc:
            msg = f"[API_ERROR] LangGraph returned {exc.response.status_code}: {exc.response.text[:200]}"
            log.error(msg)
            return msg
        except Exception as exc:
            msg = f"[INVOKE_ERROR] Unexpected error invoking {agent_name}: {exc}"
            log.error(msg)
            return msg

    def _extract_message(self, data: object) -> str:
        """Extract the final assistant message text from a LangGraph run response."""
        if not isinstance(data, dict):
            return str(data)

        # LangGraph run result: {"output": {"messages": [...]}}
        output = data.get("output") or data
        if isinstance(output, dict):
            messages = output.get("messages", [])
            if isinstance(messages, list):
                for msg in reversed(messages):
                    if isinstance(msg, dict) and msg.get("type") == "ai":
                        content = msg.get("content", "")
                        if isinstance(content, str):
                            return content
                        if isinstance(content, list):
                            parts = [
                                c.get("text", "")
                                for c in content
                                if isinstance(c, dict) and c.get("type") == "text"
                            ]
                            return " ".join(p for p in parts if p)

        return json.dumps(data)

    def _build_attack_prompt(self, objective: Objective) -> str:
        """Build the per-iteration prompt injected into the fresh agent context."""
        assert self._state is not None

        # Summarize prior findings from disk — include title for sub-agent context
        findings_dir = self._workspace / "findings"
        prior_findings: list[str] = []
        if findings_dir.is_dir():
            for p in sorted(findings_dir.glob("FIND-*.md")):
                title = ""
                try:
                    for line in p.read_text(encoding="utf-8").splitlines():
                        if line.startswith("# "):
                            title = line[2:].strip()
                            break
                except OSError:
                    pass  # state persist failure is non-fatal
                prior_findings.append(f"{p.stem}: {title}" if title else p.stem)

        roe_path = self._workspace / "plan" / "roe.json"
        roe_scope = ""
        if roe_path.exists():
            try:
                roe_data = json.loads(roe_path.read_text(encoding="utf-8"))
                in_scope = roe_data.get("in_scope", [])
                out_of_scope = roe_data.get("out_of_scope", [])
                roe_scope = (
                    f"In-scope: {', '.join(str(s) for s in in_scope) or 'all'}\n"
                    f"Out-of-scope: {', '.join(str(s) for s in out_of_scope) or 'none'}"
                )
            except (OSError, ValueError) as exc:
                log.warning("Could not read RoE: %s", exc)

        criteria_block = "\n".join(f"  - {c}" for c in objective.acceptance_criteria)
        findings_block = (
            "\n".join(f"  - {f}" for f in prior_findings) if prior_findings else "  none yet"
        )

        return (
            f"## Ralph Iteration {self._state.iteration}\n\n"
            f"Workspace: {self._workspace}\n"
            f"Target: {self._config.target}\n\n"
            f"### Current Objective\n"
            f"ID: {objective.id}\n"
            f"Phase: {objective.phase.value}\n"
            f"Title: {objective.title}\n"
            f"Description: {objective.description}\n"
            f"OPSEC: {objective.opsec.value}"
            + (f" — {objective.opsec_notes}" if objective.opsec_notes else "")
            + f"\n"
            f"Acceptance Criteria:\n{criteria_block}\n\n"
            f"### Prior Findings\n"
            f"{findings_block}\n\n"
            + (f"### Rules of Engagement\n{roe_scope}\n\n" if roe_scope else "")
            + "Execute the objective. Write findings to workspace/findings/FIND-NNN.md. "
            "Signal OBJECTIVE PASSED or OBJECTIVE BLOCKED when done."
        )

    def _next_pending_objective(self) -> Objective | None:
        """Return the highest-priority pending objective whose dependencies are met."""
        if self._opplan is None:
            return None

        completed_ids = set(self._state.objectives_completed) if self._state else set()

        candidates = [
            obj
            for obj in self._opplan.objectives
            if obj.status == ObjectiveStatus.PENDING
            and all(dep in completed_ids for dep in obj.blocked_by)
        ]

        if not candidates:
            return None

        return min(candidates, key=lambda o: o.priority)

    def _parse_objective_result(
        self,
        response: str,
        objective: Objective,
        agent: str,
        start: float,
    ) -> IterationResult:
        """Parse OBJECTIVE PASSED/BLOCKED signal and FIND-NNN refs from agent response."""
        upper = response.upper()

        if "OBJECTIVE PASSED" in upper:
            outcome = "PASSED"
        elif "OBJECTIVE BLOCKED" in upper:
            outcome = "BLOCKED"
        else:
            # No explicit signal — treat as blocked so the loop doesn't stall
            outcome = "BLOCKED"
            log.warning(
                "Objective %s: no PASSED/BLOCKED signal in response — defaulting to BLOCKED",
                objective.id,
            )

        # Extract FIND-NNN references
        findings = re.findall(r"\bFIND-\d{3,}\b", response)
        unique_findings = list(dict.fromkeys(findings))  # preserve order, deduplicate

        return IterationResult(
            objective_id=objective.id,
            agent_used=agent,
            outcome=outcome,
            findings_produced=unique_findings,
            duration_seconds=round(time.time() - start, 2),
            raw_output=response,
        )

    def _load_opplan(self) -> OPPLAN | None:
        """Read and validate workspace/plan/opplan.json."""
        opplan_path = self._workspace / "plan" / "opplan.json"
        if not opplan_path.exists():
            log.debug("opplan.json not found at %s", opplan_path)
            return None
        try:
            data = json.loads(opplan_path.read_text(encoding="utf-8"))
            return OPPLAN.model_validate(data)
        except (OSError, ValueError) as exc:
            log.error("Failed to load opplan.json: %s", exc)
            return None

    def _update_opplan_objective(self, obj_id: str, status: ObjectiveStatus) -> None:
        """Load opplan, update one objective's status, and write back to disk."""
        opplan_path = self._workspace / "plan" / "opplan.json"
        if not opplan_path.exists():
            log.warning("Cannot update objective %s — opplan.json missing", obj_id)
            return
        try:
            data = json.loads(opplan_path.read_text(encoding="utf-8"))
            updated = False
            for obj in data.get("objectives", []):
                if obj.get("id") == obj_id:
                    obj["status"] = status.value
                    updated = True
                    break
            if updated:
                opplan_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
                log.debug("Updated objective %s → %s", obj_id, status.value)
            else:
                log.warning("Objective %s not found in opplan.json", obj_id)
        except (OSError, ValueError) as exc:
            log.error("Failed to update opplan objective %s: %s", obj_id, exc)

    def _recover_stale_objectives(self) -> None:
        """Reset any IN_PROGRESS objectives back to PENDING.

        The engagement loop marks an objective IN_PROGRESS, invokes the agent,
        then updates to COMPLETED or BLOCKED. If the process crashes between
        the first and second write, the objective is left orphaned at
        IN_PROGRESS. _next_pending_objective() only considers PENDING
        objectives, so the orphan is never retried.

        On startup, scan and reset so the loop can pick them up again.
        """
        if self._opplan is None:
            return
        stale = [o for o in self._opplan.objectives if o.status == ObjectiveStatus.IN_PROGRESS]
        if not stale:
            return
        log.warning(
            "Resetting %d stale IN_PROGRESS objective(s) to PENDING: %s",
            len(stale),
            ", ".join(o.id for o in stale),
        )
        for obj in stale:
            self._update_opplan_objective(obj.id, ObjectiveStatus.PENDING)


# ── Convenience entry point ────────────────────────────────────────────────────


async def run_engagement(
    workspace: str | Path,
    config: EngagementConfig | None = None,
) -> EngagementState:
    """Entry point for the engagement loop.

    Args:
        workspace: Path to the engagement workspace directory.
        config: Engagement configuration. If ``None``, a default config is used
                with ``target="unknown"`` — suitable for resuming an existing
                engagement where the target is already recorded in state.

    Returns:
        The final :class:`EngagementState` after the loop completes.
    """
    workspace = Path(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    if config is None:
        config = EngagementConfig(target="unknown")
    loop = EngagementLoop(workspace, config)
    return await loop.run()
